title: "Healthsea"
description: "This is the spaCy project for the Healthsea pipeline with all dataset and training workflows."
# Variables can be referenced across the project.yml using ${vars.var_name}
vars:
  version: "0.0.1"
  name: "healthsea"

  # config_tok2vec or config_trf
  config: "config_tok2vec"
  train: "train"
  dev: "dev"

  # True or False
  verbose_eval: "False"

  models:
    model_ner: "training/ner/${vars.config}/model-best"
    model_clausecat: "training/clausecat/${vars.config}/model-best"

  prodigy:
    ner_db: "healthsea_ner_annotation"

  gpu_id: -1
  eval_split: 0.25

# These are the directories that the project needs. The project CLI will make
# sure that they always exist.
directories: ["assets","training","configs","scripts","package"]

# Assets that should be downloaded or available in the directory. We're shipping
# them with the project, so they won't have to be downloaded. But the
# 'project assets' command still lets you verify that all required files are available.
assets:
  - dest: "assets/ner/annotation.jsonl"
    description: "NER annotations exported from Prodigy with 5000 examples and 2 labels"
  - dest: "assets/ner/train.spacy"
    description: "Training dataset for NER"
  - dest: "assets/ner/dev.spacy"
    description: "Development dataset for NER"
  - dest: "assets/clausecat/annotation.jsonl"
    description: "Annotations exported from Prodigy with 5000 examples and 4 classes"
  - dest: "assets/clausecat/train.spacy"
    description: "Training dataset for Clausecat (Text Classification)"
  - dest: "assets/clausecat/dev.spacy"
    description: "Development dataset for Clausecat (Text Classification)"
  - dest: "assets/end_to_end_evaluation.json"
    description: "End-to-end evaluation dataset"
  - dest: "assets/pretrained_weights_ner.bin"
    description: "Pretrained weights trained on IHerb reviews for initializing NER tok2vec"
  - dest: "assets/pretrained_weights_clausecat.bin"
    description: "Pretrained weights trained on IHerb reviews for initializing Clausecat tok2vec"

# Workflows are sequences of commands (see below) executed in order. You can
# run them via "spacy project run [workflow]". If a commands's inputs/outputs
# haven't changed, it won't be re-run.
workflows:
  install:
    - requirements
  process_ner:
    - analyze_ner
    - train_ner
    - evaluate_ner
  process_clausecat:
    - parse_clausecat
    - train_clausecat
    - evaluate_clausecat

# Project commands, specified in a style similar to CI config files (e.g. Azure
# pipelines). The name is the command name that lets you trigger the command
# via "spacy project run [command] [path]". The help message is optional and
# shown when executing "spacy project run [optional command] [path] --help".
commands:
  - name: "requirements"
    help: "Install dependencies and requirements"
    script:
      - "pip install -r requirements.txt"
      - "python -m spacy download en_core_web_lg"
      - "python scripts/benepar_download.py"

  # Works only with prodigy. Can be skipped otherwise, as the training files for the NER are already available in the assets folder
  - name: "parse_ner"
    help: "Load the annotations to Prodigy and use data-to-spacy to split the data into a training and development set"
    script:
      - "python scripts/check_prodigy.py"
      - "python -m prodigy db-in ${vars.prodigy.ner_db} assets/ner/annotation.jsonl"
      - "python -m prodigy data-to-spacy assets/ner/ -n ${vars.prodigy.ner_db} -es ${vars.eval_split}"
    deps:
      - "assets/ner/annotation.jsonl"
    outputs:
      - "data/ner/${vars.train}.spacy"
      - "data/ner/${vars.dev}.spacy"

  - name: "analyze_ner"
    help: "Analyze the NER annotation dataset"
    script:
      - "python scripts/parsing/analyze_ner_annotation.py assets/ner/annotation.jsonl"
    deps:
      - "assets/ner/annotation.jsonl"

  - name: "train_ner"
    help: "Train an NER model"
    script:
      - "python -m spacy train configs/ner/${vars.config}.cfg --output training/ner/${vars.config}/ --paths.train assets/ner/${vars.train}.spacy --paths.dev assets/ner/${vars.dev}.spacy --paths.init_tok2vec assets/pretrained_weights_ner.bin --gpu-id ${vars.gpu_id}"
    deps:
      - "assets/ner/${vars.train}.spacy"
      - "assets/ner/${vars.dev}.spacy"
    outputs:
      - ${vars.models.model_ner}

  - name: "evaluate_ner"
    help: "Evaluate the trained NER model"
    script:
      - "python -m spacy evaluate ${vars.models.model_ner} assets/ner/${vars.dev}.spacy --gpu-id ${vars.gpu_id}"
    deps:
      - "assets/ner/${vars.dev}.spacy"
      - ${vars.models.model_ner}

  # You can skip this command if you're happy with the training files in the assets folder generated with the default split
  - name: "parse_clausecat"
    help: "Parse the textcat annotations into clausecat format and split into training and development set"
    script:
      - "python scripts/parsing/parse_clausecat.py assets/clausecat/annotation.jsonl assets/clausecat/${vars.train}.spacy assets/clausecat/${vars.dev}.spacy ${vars.eval_split}"
    deps:
      - "assets/clausecat/annotation.jsonl"
    outputs:
      - "assets/clausecat/${vars.train}.spacy"
      - "assets/clausecat/${vars.dev}.spacy"

  - name: "train_clausecat"
    help: "Train the custom Clausecat component"
    script:
      - "python -m spacy train configs/clausecat/${vars.config}.cfg --output training/clausecat/${vars.config}/ -c scripts/clausecat/custom_code.py --paths.train assets/clausecat/${vars.train}.spacy --paths.dev assets/clausecat/${vars.dev}.spacy --paths.init_tok2vec assets/pretrained_weights_clausecat.bin --gpu-id ${vars.gpu_id} --paths.ner_model ${vars.models.model_ner}"
    deps:
      - "configs/clausecat/${vars.config}.cfg"
      - "assets/clausecat/${vars.train}.spacy"
      - "assets/clausecat/${vars.dev}.spacy"
    outputs:
      - ${vars.models.model_clausecat}

  - name: "evaluate_clausecat"
    help: "Evaluate the trained Clausecat component"
    script:
      - "python scripts/evaluate_clausecat.py ${vars.models.model_clausecat} assets/clausecat/${vars.dev}.spacy"
    deps:
      - ${vars.models.model_clausecat}
      - "assets/clausecat/${vars.dev}.spacy"

  - name: "evaluate"
    help: "Evaluate the healthsea pipeline"
    script:
      - "python scripts/end_to_end_evaluation.py ${vars.models.model_clausecat} assets/end_to_end_evaluation.json ${vars.verbose_eval}"
    deps:
      - ${vars.models.model_clausecat}

  - name: "package"
    help: "Package your trained healthsea pipeline"
    script:
      - "python -m spacy package ${vars.models.model_clausecat} package --code scripts/clausecat/clause_aggregation.py,scripts/clausecat/clause_segmentation.py,scripts/clausecat/clausecat_component.py,scripts/clausecat/clausecat_model.py,scripts/clausecat/clausecat_reader.py --name healthsea --create-meta --build wheel --force"
    deps:
      - ${vars.models.model_clausecat}

  - name: "reset"
    help: "Reset the project to its original state and delete all training process"
    script:
      - "python scripts/reset.py training/ner"
      - "python scripts/reset.py training/clausecat"
      - "python scripts/reset.py package"
